# swoop 0.13.0. Generated by scripts/tap-formula in beatzball/swoop on every
# release: change it there, not here.
class Swoop < Formula
  desc "Keyboard launcher built the Unix way: fzf finds, extensions print lines"
  homepage "https://github.com/beatzball/swoop"
  license "MIT"

  depends_on "fzf"

  on_macos do
    on_arm do
      url "https://github.com/beatzball/swoop/releases/download/v0.13.0/swoop-0.13.0-darwin-arm64.tar.gz"
      sha256 "e442664e13e882bc9005a69fab697863e6e0bcdd43446f7750f0e1a1f333a51b"
    end
    on_intel do
      url "https://github.com/beatzball/swoop/releases/download/v0.13.0/swoop-0.13.0-darwin-amd64.tar.gz"
      sha256 "30d487c7bd157686795a171901ea28ad1bec688eb908ce27025935046eaacfed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/beatzball/swoop/releases/download/v0.13.0/swoop-0.13.0-linux-arm64.tar.gz"
      sha256 "3f32192afeb9a894a82850e1a1b5ab8f9b2a95c936785477dfa2f854e9af6d35"
    end
    on_intel do
      url "https://github.com/beatzball/swoop/releases/download/v0.13.0/swoop-0.13.0-linux-amd64.tar.gz"
      sha256 "1c2f257859fd039b3d9d28b32ba7b957008437d90a52bc7971396c826359daf1"
    end
  end

  def install
    # The tarball stays whole under libexec: bin/swoop finds its tools
    # beside itself and the extensions at ../extensions, and the frame
    # needs its resource bundle beside it. Only the commands are linked.
    libexec.install Dir["*"]
    Dir[libexec/"bin/swoop*"].each do |f|
      next if File.basename(f) == "swoop-shell-mac"

      bin.install_symlink f
    end
  end

  # The frame: a panel on alt+shift+space, at login, on a Mac. The
  # clipboard watcher starts itself the first time the launcher runs.
  service do
    run macos: [opt_libexec/"bin/swoop-shell-mac"]
    keep_alive true
    process_type :interactive
    environment_variables PATH: std_service_path_env, SWOOP_LAUNCHER: opt_libexec/"bin/swoop"
    log_path var/"log/swoop.log"
    error_log_path var/"log/swoop.log"
  end

  def caveats
    <<~EOS
      In any terminal, on any OS: swoop

      On a Mac, the frame (a panel on alt+shift+space) runs at login with:
        brew services start swoop
      After that, swoop restart, swoop stop, swoop start, swoop status;
      the bird in the menu bar has Restart and Quit.

      After each upgrade, remove swoop-shell-mac from System Settings,
      Privacy & Security, Accessibility and add it again: releases are
      not signed yet, so a new version needs a new grant.

      The service sees Homebrew's PATH only. If your AI command lives
      elsewhere, name it in full in ~/.config/swoop/ai, for example:
        ~/.local/bin/claude -p
    EOS
  end

  test do
    assert_match "hi", pipe_output("#{bin}/swoop-md -w 40", "# hi\n")
    assert_equal "0.13.0", (libexec/"VERSION").read.strip
  end
end
