# swoop 0.7.0. Generated by scripts/tap-formula in beatzball/swoop on every
# release: change it there, not here.
class Swoop < Formula
  desc "Keyboard launcher built the Unix way: fzf finds, extensions print lines"
  homepage "https://github.com/beatzball/swoop"
  license "MIT"

  depends_on "fzf"

  on_macos do
    on_arm do
      url "https://github.com/beatzball/swoop/releases/download/v0.7.0/swoop-0.7.0-darwin-arm64.tar.gz"
      sha256 "d2d1fba0d307f178dbf923ee2478d6d1e5a141ffdccd567d2514ea395a22fa99"
    end
    on_intel do
      url "https://github.com/beatzball/swoop/releases/download/v0.7.0/swoop-0.7.0-darwin-amd64.tar.gz"
      sha256 "3e086966daa930d6bcf6c3eb7aed6e9602a4184a722e78b2e0fefd85b6fff250"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/beatzball/swoop/releases/download/v0.7.0/swoop-0.7.0-linux-arm64.tar.gz"
      sha256 "97649cfd74f41292355dc97edb9022c468962715c3ea6fd61b15455aefd7bdbc"
    end
    on_intel do
      url "https://github.com/beatzball/swoop/releases/download/v0.7.0/swoop-0.7.0-linux-amd64.tar.gz"
      sha256 "ce76445c08fbf16298a7f96a8dfc99a324f5cdfd0b414aa904675ab7b32858f4"
    end
  end

  def install
    # The tarball stays whole under libexec: bin/swoop finds its tools
    # beside itself and the extensions at ../extensions, and the frame
    # needs its resource bundle beside it. Only the commands are linked.
    libexec.install Dir["*"]
    Dir[libexec/"bin/swoop*"].each do |f|
      next if File.basename(f) == "swoop-shell-mac"

      bin.install_symlink f
    end
  end

  # The frame: a panel on alt+shift+space, at login, on a Mac. The
  # clipboard watcher starts itself the first time the launcher runs.
  service do
    run macos: [opt_libexec/"bin/swoop-shell-mac"]
    keep_alive true
    process_type :interactive
    environment_variables PATH: std_service_path_env, SWOOP_LAUNCHER: opt_libexec/"bin/swoop"
    log_path var/"log/swoop.log"
    error_log_path var/"log/swoop.log"
  end

  def caveats
    <<~EOS
      In any terminal, on any OS: swoop

      On a Mac, the frame (a panel on alt+shift+space) runs at login with:
        brew services start swoop

      The service sees Homebrew's PATH only. If your AI command lives
      elsewhere, name it in full in ~/.config/swoop/ai, for example:
        ~/.local/bin/claude -p
    EOS
  end

  test do
    assert_match "hi", pipe_output("#{bin}/swoop-md -w 40", "# hi\n")
    assert_equal "0.7.0", (libexec/"VERSION").read.strip
  end
end
