# swoop 0.10.0. Generated by scripts/tap-formula in beatzball/swoop on every
# release: change it there, not here.
class Swoop < Formula
  desc "Keyboard launcher built the Unix way: fzf finds, extensions print lines"
  homepage "https://github.com/beatzball/swoop"
  license "MIT"

  depends_on "fzf"

  on_macos do
    on_arm do
      url "https://github.com/beatzball/swoop/releases/download/v0.10.0/swoop-0.10.0-darwin-arm64.tar.gz"
      sha256 "3d6312735abac8da24dae94a03ef5dd49d19073649d11b05adbcb06af8ade9fb"
    end
    on_intel do
      url "https://github.com/beatzball/swoop/releases/download/v0.10.0/swoop-0.10.0-darwin-amd64.tar.gz"
      sha256 "71fbf680c612366e1e3083e471ec5f5a4d36b8a09bfbed7232acb5d53e014eb6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/beatzball/swoop/releases/download/v0.10.0/swoop-0.10.0-linux-arm64.tar.gz"
      sha256 "b88f597f2c517e3fb5d0d8e8e683cc41cdfa9fde79b33962491aea903c5431a3"
    end
    on_intel do
      url "https://github.com/beatzball/swoop/releases/download/v0.10.0/swoop-0.10.0-linux-amd64.tar.gz"
      sha256 "6885e1b34054846f92864a549f695722e48b6d6dfbf72e3ee87bd951dcf5335a"
    end
  end

  def install
    # The tarball stays whole under libexec: bin/swoop finds its tools
    # beside itself and the extensions at ../extensions, and the frame
    # needs its resource bundle beside it. Only the commands are linked.
    libexec.install Dir["*"]
    Dir[libexec/"bin/swoop*"].each do |f|
      next if File.basename(f) == "swoop-shell-mac"

      bin.install_symlink f
    end
  end

  # The frame: a panel on alt+shift+space, at login, on a Mac. The
  # clipboard watcher starts itself the first time the launcher runs.
  service do
    run macos: [opt_libexec/"bin/swoop-shell-mac"]
    keep_alive true
    process_type :interactive
    environment_variables PATH: std_service_path_env, SWOOP_LAUNCHER: opt_libexec/"bin/swoop"
    log_path var/"log/swoop.log"
    error_log_path var/"log/swoop.log"
  end

  def caveats
    <<~EOS
      In any terminal, on any OS: swoop

      On a Mac, the frame (a panel on alt+shift+space) runs at login with:
        brew services start swoop
      After that, swoop restart, swoop stop, swoop start, swoop status;
      the bird in the menu bar has Restart and Quit.

      After each upgrade, remove swoop-shell-mac from System Settings,
      Privacy & Security, Accessibility and add it again: releases are
      not signed yet, so a new version needs a new grant.

      The service sees Homebrew's PATH only. If your AI command lives
      elsewhere, name it in full in ~/.config/swoop/ai, for example:
        ~/.local/bin/claude -p
    EOS
  end

  test do
    assert_match "hi", pipe_output("#{bin}/swoop-md -w 40", "# hi\n")
    assert_equal "0.10.0", (libexec/"VERSION").read.strip
  end
end
